# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/adrien/IDEs/clion-2016.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/adrien/IDEs/clion-2016.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adrien/repo/programme_10

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adrien/repo/programme_10

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/adrien/IDEs/clion-2016.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/adrien/IDEs/clion-2016.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adrien/repo/programme_10/CMakeFiles /home/adrien/repo/programme_10/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adrien/repo/programme_10/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named executable

# Build rule for target.
executable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executable
.PHONY : executable

# fast build rule for target.
executable/fast:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/build
.PHONY : executable/fast

src/CameraObject.o: src/CameraObject.cpp.o

.PHONY : src/CameraObject.o

# target to build an object file
src/CameraObject.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/CameraObject.cpp.o
.PHONY : src/CameraObject.cpp.o

src/CameraObject.i: src/CameraObject.cpp.i

.PHONY : src/CameraObject.i

# target to preprocess a source file
src/CameraObject.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/CameraObject.cpp.i
.PHONY : src/CameraObject.cpp.i

src/CameraObject.s: src/CameraObject.cpp.s

.PHONY : src/CameraObject.s

# target to generate assembly for a file
src/CameraObject.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/CameraObject.cpp.s
.PHONY : src/CameraObject.cpp.s

src/Data.o: src/Data.cpp.o

.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i

.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s

.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/GameData.o: src/GameData.cpp.o

.PHONY : src/GameData.o

# target to build an object file
src/GameData.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameData.cpp.o
.PHONY : src/GameData.cpp.o

src/GameData.i: src/GameData.cpp.i

.PHONY : src/GameData.i

# target to preprocess a source file
src/GameData.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameData.cpp.i
.PHONY : src/GameData.cpp.i

src/GameData.s: src/GameData.cpp.s

.PHONY : src/GameData.s

# target to generate assembly for a file
src/GameData.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameData.cpp.s
.PHONY : src/GameData.cpp.s

src/GameObject.o: src/GameObject.cpp.o

.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i

.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s

.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/GameState.o: src/GameState.cpp.o

.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i

.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s

.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/GroundModel.o: src/GroundModel.cpp.o

.PHONY : src/GroundModel.o

# target to build an object file
src/GroundModel.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GroundModel.cpp.o
.PHONY : src/GroundModel.cpp.o

src/GroundModel.i: src/GroundModel.cpp.i

.PHONY : src/GroundModel.i

# target to preprocess a source file
src/GroundModel.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GroundModel.cpp.i
.PHONY : src/GroundModel.cpp.i

src/GroundModel.s: src/GroundModel.cpp.s

.PHONY : src/GroundModel.s

# target to generate assembly for a file
src/GroundModel.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/GroundModel.cpp.s
.PHONY : src/GroundModel.cpp.s

src/KeyboardHandler.o: src/KeyboardHandler.cpp.o

.PHONY : src/KeyboardHandler.o

# target to build an object file
src/KeyboardHandler.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/KeyboardHandler.cpp.o
.PHONY : src/KeyboardHandler.cpp.o

src/KeyboardHandler.i: src/KeyboardHandler.cpp.i

.PHONY : src/KeyboardHandler.i

# target to preprocess a source file
src/KeyboardHandler.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/KeyboardHandler.cpp.i
.PHONY : src/KeyboardHandler.cpp.i

src/KeyboardHandler.s: src/KeyboardHandler.cpp.s

.PHONY : src/KeyboardHandler.s

# target to generate assembly for a file
src/KeyboardHandler.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/KeyboardHandler.cpp.s
.PHONY : src/KeyboardHandler.cpp.s

src/LabyModel.o: src/LabyModel.cpp.o

.PHONY : src/LabyModel.o

# target to build an object file
src/LabyModel.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/LabyModel.cpp.o
.PHONY : src/LabyModel.cpp.o

src/LabyModel.i: src/LabyModel.cpp.i

.PHONY : src/LabyModel.i

# target to preprocess a source file
src/LabyModel.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/LabyModel.cpp.i
.PHONY : src/LabyModel.cpp.i

src/LabyModel.s: src/LabyModel.cpp.s

.PHONY : src/LabyModel.s

# target to generate assembly for a file
src/LabyModel.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/LabyModel.cpp.s
.PHONY : src/LabyModel.cpp.s

src/MapObject.o: src/MapObject.cpp.o

.PHONY : src/MapObject.o

# target to build an object file
src/MapObject.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/MapObject.cpp.o
.PHONY : src/MapObject.cpp.o

src/MapObject.i: src/MapObject.cpp.i

.PHONY : src/MapObject.i

# target to preprocess a source file
src/MapObject.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/MapObject.cpp.i
.PHONY : src/MapObject.cpp.i

src/MapObject.s: src/MapObject.cpp.s

.PHONY : src/MapObject.s

# target to generate assembly for a file
src/MapObject.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/MapObject.cpp.s
.PHONY : src/MapObject.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/State.o: src/State.cpp.o

.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i

.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s

.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

src/View.o: src/View.cpp.o

.PHONY : src/View.o

# target to build an object file
src/View.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/View.cpp.o
.PHONY : src/View.cpp.o

src/View.i: src/View.cpp.i

.PHONY : src/View.i

# target to preprocess a source file
src/View.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/View.cpp.i
.PHONY : src/View.cpp.i

src/View.s: src/View.cpp.s

.PHONY : src/View.s

# target to generate assembly for a file
src/View.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/View.cpp.s
.PHONY : src/View.cpp.s

src/format/mesh_io_obj.o: src/format/mesh_io_obj.cpp.o

.PHONY : src/format/mesh_io_obj.o

# target to build an object file
src/format/mesh_io_obj.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_obj.cpp.o
.PHONY : src/format/mesh_io_obj.cpp.o

src/format/mesh_io_obj.i: src/format/mesh_io_obj.cpp.i

.PHONY : src/format/mesh_io_obj.i

# target to preprocess a source file
src/format/mesh_io_obj.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_obj.cpp.i
.PHONY : src/format/mesh_io_obj.cpp.i

src/format/mesh_io_obj.s: src/format/mesh_io_obj.cpp.s

.PHONY : src/format/mesh_io_obj.s

# target to generate assembly for a file
src/format/mesh_io_obj.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_obj.cpp.s
.PHONY : src/format/mesh_io_obj.cpp.s

src/format/mesh_io_off.o: src/format/mesh_io_off.cpp.o

.PHONY : src/format/mesh_io_off.o

# target to build an object file
src/format/mesh_io_off.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_off.cpp.o
.PHONY : src/format/mesh_io_off.cpp.o

src/format/mesh_io_off.i: src/format/mesh_io_off.cpp.i

.PHONY : src/format/mesh_io_off.i

# target to preprocess a source file
src/format/mesh_io_off.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_off.cpp.i
.PHONY : src/format/mesh_io_off.cpp.i

src/format/mesh_io_off.s: src/format/mesh_io_off.cpp.s

.PHONY : src/format/mesh_io_off.s

# target to generate assembly for a file
src/format/mesh_io_off.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/format/mesh_io_off.cpp.s
.PHONY : src/format/mesh_io_off.cpp.s

src/glutils.o: src/glutils.cpp.o

.PHONY : src/glutils.o

# target to build an object file
src/glutils.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/glutils.cpp.o
.PHONY : src/glutils.cpp.o

src/glutils.i: src/glutils.cpp.i

.PHONY : src/glutils.i

# target to preprocess a source file
src/glutils.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/glutils.cpp.i
.PHONY : src/glutils.cpp.i

src/glutils.s: src/glutils.cpp.s

.PHONY : src/glutils.s

# target to generate assembly for a file
src/glutils.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/glutils.cpp.s
.PHONY : src/glutils.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mat4.o: src/mat4.cpp.o

.PHONY : src/mat4.o

# target to build an object file
src/mat4.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mat4.cpp.o
.PHONY : src/mat4.cpp.o

src/mat4.i: src/mat4.cpp.i

.PHONY : src/mat4.i

# target to preprocess a source file
src/mat4.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mat4.cpp.i
.PHONY : src/mat4.cpp.i

src/mat4.s: src/mat4.cpp.s

.PHONY : src/mat4.s

# target to generate assembly for a file
src/mat4.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mat4.cpp.s
.PHONY : src/mat4.cpp.s

src/mesh.o: src/mesh.cpp.o

.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i

.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s

.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/tga.o: src/tga.cpp.o

.PHONY : src/tga.o

# target to build an object file
src/tga.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/tga.cpp.o
.PHONY : src/tga.cpp.o

src/tga.i: src/tga.cpp.i

.PHONY : src/tga.i

# target to preprocess a source file
src/tga.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/tga.cpp.i
.PHONY : src/tga.cpp.i

src/tga.s: src/tga.cpp.s

.PHONY : src/tga.s

# target to generate assembly for a file
src/tga.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/tga.cpp.s
.PHONY : src/tga.cpp.s

src/triangle_index.o: src/triangle_index.cpp.o

.PHONY : src/triangle_index.o

# target to build an object file
src/triangle_index.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/triangle_index.cpp.o
.PHONY : src/triangle_index.cpp.o

src/triangle_index.i: src/triangle_index.cpp.i

.PHONY : src/triangle_index.i

# target to preprocess a source file
src/triangle_index.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/triangle_index.cpp.i
.PHONY : src/triangle_index.cpp.i

src/triangle_index.s: src/triangle_index.cpp.s

.PHONY : src/triangle_index.s

# target to generate assembly for a file
src/triangle_index.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/triangle_index.cpp.s
.PHONY : src/triangle_index.cpp.s

src/vec2.o: src/vec2.cpp.o

.PHONY : src/vec2.o

# target to build an object file
src/vec2.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec2.cpp.o
.PHONY : src/vec2.cpp.o

src/vec2.i: src/vec2.cpp.i

.PHONY : src/vec2.i

# target to preprocess a source file
src/vec2.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec2.cpp.i
.PHONY : src/vec2.cpp.i

src/vec2.s: src/vec2.cpp.s

.PHONY : src/vec2.s

# target to generate assembly for a file
src/vec2.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec2.cpp.s
.PHONY : src/vec2.cpp.s

src/vec3.o: src/vec3.cpp.o

.PHONY : src/vec3.o

# target to build an object file
src/vec3.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec3.cpp.o
.PHONY : src/vec3.cpp.o

src/vec3.i: src/vec3.cpp.i

.PHONY : src/vec3.i

# target to preprocess a source file
src/vec3.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec3.cpp.i
.PHONY : src/vec3.cpp.i

src/vec3.s: src/vec3.cpp.s

.PHONY : src/vec3.s

# target to generate assembly for a file
src/vec3.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vec3.cpp.s
.PHONY : src/vec3.cpp.s

src/vertex_opengl.o: src/vertex_opengl.cpp.o

.PHONY : src/vertex_opengl.o

# target to build an object file
src/vertex_opengl.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vertex_opengl.cpp.o
.PHONY : src/vertex_opengl.cpp.o

src/vertex_opengl.i: src/vertex_opengl.cpp.i

.PHONY : src/vertex_opengl.i

# target to preprocess a source file
src/vertex_opengl.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vertex_opengl.cpp.i
.PHONY : src/vertex_opengl.cpp.i

src/vertex_opengl.s: src/vertex_opengl.cpp.s

.PHONY : src/vertex_opengl.s

# target to generate assembly for a file
src/vertex_opengl.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/vertex_opengl.cpp.s
.PHONY : src/vertex_opengl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... executable"
	@echo "... src/CameraObject.o"
	@echo "... src/CameraObject.i"
	@echo "... src/CameraObject.s"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/GameData.o"
	@echo "... src/GameData.i"
	@echo "... src/GameData.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/GroundModel.o"
	@echo "... src/GroundModel.i"
	@echo "... src/GroundModel.s"
	@echo "... src/KeyboardHandler.o"
	@echo "... src/KeyboardHandler.i"
	@echo "... src/KeyboardHandler.s"
	@echo "... src/LabyModel.o"
	@echo "... src/LabyModel.i"
	@echo "... src/LabyModel.s"
	@echo "... src/MapObject.o"
	@echo "... src/MapObject.i"
	@echo "... src/MapObject.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
	@echo "... src/View.o"
	@echo "... src/View.i"
	@echo "... src/View.s"
	@echo "... src/format/mesh_io_obj.o"
	@echo "... src/format/mesh_io_obj.i"
	@echo "... src/format/mesh_io_obj.s"
	@echo "... src/format/mesh_io_off.o"
	@echo "... src/format/mesh_io_off.i"
	@echo "... src/format/mesh_io_off.s"
	@echo "... src/glutils.o"
	@echo "... src/glutils.i"
	@echo "... src/glutils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mat4.o"
	@echo "... src/mat4.i"
	@echo "... src/mat4.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/tga.o"
	@echo "... src/tga.i"
	@echo "... src/tga.s"
	@echo "... src/triangle_index.o"
	@echo "... src/triangle_index.i"
	@echo "... src/triangle_index.s"
	@echo "... src/vec2.o"
	@echo "... src/vec2.i"
	@echo "... src/vec2.s"
	@echo "... src/vec3.o"
	@echo "... src/vec3.i"
	@echo "... src/vec3.s"
	@echo "... src/vertex_opengl.o"
	@echo "... src/vertex_opengl.i"
	@echo "... src/vertex_opengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

